#!/bin/bash
../random-utils/run_sbatch.py 'EntNet.py --tasks=1 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task1.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=2 --train --n_tries=10' --gpu=1 --mem=2048m --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task2.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=3 --train --n_tries=10' --gpu=1 --mem=2048m --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task3.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=4 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task4.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=5 --train --n_tries=10' --gpu=1 --mem=2048m --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task5.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=6 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task6.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=7 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task7.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=8 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task8.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=9 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task9.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=10 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task10.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=11 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task11.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=12 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task12.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=13 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task13.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=14 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task14.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=15 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task15.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=16 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task16.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=17 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task17.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=18 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task18.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=19 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task19.out"
../random-utils/run_sbatch.py 'EntNet.py --tasks=20 --train --n_tries=10' --gpu=1 --time=24:0:0 --output="/cs/labs/dshahaf/aviadsa/entnet_project/entnet_babi_remote/script_results/task20.out"

